import './polyfill';

import _bindActions from './bindActions';
import _callAsync from './callAsync';
import _cancelEvent from './cancelEvent';
import _colors from './colors';
import _combineObjects from './combineObjects';
import _debounce from './debounce';
import _deleteObjectProperty from './deleteObjectProperty';
import _dragInfo from './dragInfo';
import _fastClick from './fastClick';
import fastDate from './fastDate';
import _getCoords from './getCoords';
import _getDeepClone from './getDeepClone';
import _getDeepProp from './getDeepProp';
import _getTime from './getTime';
import _groupByKey from './groupByKey';
import _makeCancelable from './makeCancelable';
import _mergeProps from './mergeProps';
import _performance from './performance';
import _stringUtils from './stringUtils';
import _throttle from './throttle';

export const bindActions = _bindActions;
export const callAsync = _callAsync;
export const cancelEvent = _cancelEvent;
export const colors = _colors;
export const combineObjects = _combineObjects;
export const debounce = _debounce;
export const deleteObjectProperty = _deleteObjectProperty;
export const dragInfo = _dragInfo;
export const fastClick = _fastClick;
export const FastDate = fastDate; //yes, it's a class, so Pascal case
export const groupByKey = _groupByKey;
export const getCoords = _getCoords;
export const getDeepClone = _getDeepClone;
export const getDeepProp = _getDeepProp;
export const getTime = _getTime;
export const makeCancelable = _makeCancelable;
export const mergeProps = _mergeProps;
export const performance = _performance;
export const stringUtils = _stringUtils;
export const throttle = _throttle;
