import './polyf';

import _bindActions from './bindActions';
import _boolUtils from './boolUtils';
import _cancelEvent from './cancelEvent';
import _colors from './colors';
import _dateUtils from './dateUtils';
import _debounce from './debounce';
import _dragInfo from './dragInfo';
import _fastClick from './fastClick';
import fastDate from './fastDate';
import _formatNegativeValues from './formatNegativeValues';
import _getCoords from './getCoords';
import _getDeepClone from './getDeepClone';
import _getDeepProp from './getDeepProp';
import _getTime from './getTime';
import _groupByKey from './groupByKey';
import _languageUtils from './language';
import _makeCancelable from './makeCancelable';
import _mergeProps from './mergeProps';
import _stringUtils from './stringUtils';
import _throttle from './throttle';
import _updateSearchFilter from './updateSearchFilter';

export const bindActions = _bindActions;
export const boolUtils = _boolUtils;
export const cancelEvent = _cancelEvent;
export const colors = _colors;
export const dateUtils = _dateUtils;
export const debounce = _debounce;
export const dragInfo = _dragInfo;
export const fastClick = _fastClick;
export const FastDate = fastDate; //yes, it's a class, so Pascal case
export const formatNegativeValues = _formatNegativeValues;
export const groupByKey = _groupByKey;
export const getCoords = _getCoords;
export const getDeepClone = _getDeepClone;
export const getDeepProp = _getDeepProp;
export const getTime = _getTime;
export const languageUtils = _languageUtils;
export const makeCancelable = _makeCancelable;
export const mergeProps = _mergeProps;
export const stringUtils = _stringUtils;
export const throttle = _throttle;
export const updateSearchFilter = _updateSearchFilter;